### ISSUE TITLE
difference with Just and support of i18n for messages?

### ISSUE THREAD

**Issue by lanyusan** [zaaack/foy#16]
I am using Just on a project but I need the task runner be able to provide non-english messages when running tasks. It seems Just doesn't support that.

I am looking at other task runners. What is the difference between foy and Just and does foy support i18n for messages?

Thanks.

**Comment by zaaack** [comment]
@lanyusan Foy is a light-weight task runner which can be highly customized.  I didn't use Just before, but it's API looks quite like foy, I guess neither Just nor foy has built-in support for i18n messsages. 

But, you can using i18n library with foy to customize the messages because almose all messages are defined in Foyfile.ts, e.g.


```ts
import i18next from 'i18next'
before(() => {
  i18next.init({
    lng: 'zh',
    resources: {
      zh: {
        translation: {
          'hello world': '你好，世界',
          'custom names': '自定义名称'
        },
      },
    },
  })
})
option('-n, --name <val>', i18next.t('custom names'))
task('i18n', async (ctx) => {
  logger.info(i18next.t('hello world'))
})
```
then, run the task:
```sh
$ npx foy i18n
DependencyGraph for task [i18n]:
─ i18n

Task: i18n
[info] 你好，世界
```

**Comment by lanyusan** [comment]
原来是老乡...
